In [ ]:
# https://www.kaggle.com/prateekmaj21/tf-idf-in-python

In [ ]:
text=["kolkata big city india trade","mumbai financial capital india","delhi capital india","kolkata capital colonial times",
     "bangalore tech hub india software","mumbai hub trade commerce stock exchange","kolkata victoria memorial","delhi india gate",
      "mumbai gate way india trade business","delhi red fort india","kolkata metro oldest india",
      "delhi metro largest metro network india"]


In [ ]:
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
#using the count vectorizer
count = CountVectorizer()
word_count=count.fit_transform(text)
print(word_count)

  (0, 14)	1
  (0, 1)	1
  (0, 4)	1
  (0, 13)	1
  (0, 26)	1
  (1, 13)	1
  (1, 18)	1
  (1, 9)	1
  (1, 3)	1
  (2, 13)	1
  (2, 3)	1
  (2, 7)	1
  (3, 14)	1
  (3, 3)	1
  (3, 5)	1
  (3, 25)	1
  (4, 13)	1
  (4, 0)	1
  (4, 24)	1
  (4, 12)	1
  (4, 22)	1
  (5, 26)	1
  (5, 18)	1
  (5, 12)	1
  (5, 6)	1
  :	:
  (6, 14)	1
  (6, 27)	1
  (6, 16)	1
  (7, 13)	1
  (7, 7)	1
  (7, 11)	1
  (8, 13)	1
  (8, 26)	1
  (8, 18)	1
  (8, 11)	1
  (8, 28)	1
  (8, 2)	1
  (9, 13)	1
  (9, 7)	1
  (9, 21)	1
  (9, 10)	1
  (10, 14)	1
  (10, 13)	1
  (10, 17)	1
  (10, 20)	1
  (11, 13)	1
  (11, 7)	1
  (11, 17)	2
  (11, 15)	1
  (11, 19)	1


In [ ]:
print(word_count.toarray())

[[0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 2 0 1 0 0 0 0 0 0 0 0 0]]


In [ ]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)
df_idf = pd.DataFrame(tfidf_transformer.idf_, index=count.get_feature_names(),columns=["idf_weights"])


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
#inverse document frequency
df_idf.sort_values(by=['idf_weights']).head(3)

idf_weights
india       1.262364
kolkata     1.955511
delhi       1.955511

In [ ]:
#tfidf
tf_idf_vector=tfidf_transformer.transform(word_count)
feature_names = count.get_feature_names()
first_document_vector=tf_idf_vector[1]
df_tfifd= pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df_tfifd.sort_values(by=["tfidf"],ascending=False).head(5)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


tfidf
financial  0.653123
capital    0.495483
mumbai     0.495483
india      0.287095
bangalore  0.000000

Задание 1. Реализовать tfidf датасета 

In [ ]:
# выгружаем датасет:
!wget https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 -O ./quora.txt -nc

File ‘./quora.txt’ already there; not retrieving.


In [ ]:
data = list(open("./quora.txt", encoding="utf-8"))

In [ ]:
!pip install --upgrade nltk gensim bokeh umap-learn

import itertools
import string

import numpy as np
import umap
from nltk.tokenize import WordPunctTokenizer

from matplotlib import pyplot as plt

from IPython.display import clear_output

In [ ]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [ ]:
tokenizer = WordPunctTokenizer()

In [ ]:
data_tok = []
for line in data[0:50]:
  lst = [x.lower() for x in tokenizer.tokenize(line)]
  data_tok.append(lst)

In [ ]:
lem_words = []

for tokens in data_tok:
  str = ''
  for word in tokens: 
    str += lemmatizer.lemmatize(word) + " "
  lem_words.append(str)


In [ ]:
text = lem_words

In [ ]:
#using the count vectorizer
count = CountVectorizer()
word_count=count.fit_transform(text)
print(word_count)

In [ ]:
#print(word_count.toarray())

In [ ]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)
df_idf = pd.DataFrame(tfidf_transformer.idf_, index=count.get_feature_names(),columns=["idf_weights"])


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
#inverse document frequency
df_idf.sort_values(by=['idf_weights']).head(5)

idf_weights
the      2.041454
is       2.159237
how      2.159237
what     2.223775
can      2.446919

In [ ]:
#tfidf
tf_idf_vector=tfidf_transformer.transform(word_count)
feature_names = count.get_feature_names()
first_document_vector=tf_idf_vector[1]
df_tfifd= pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df_tfifd.sort_values(by=["tfidf"],ascending=False).head(5)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


tfidf
overcome   0.380602
food       0.380602
fast       0.380602
addiction  0.380602
some       0.380602

# Дополнительное задание. Найти наиболее близкие вектора/строки среди первых 50 строк quora

In [ ]:
matrix = word_count.toarray()

In [ ]:
cos_i_j = [0, 0, 0]
for i in range(len(matrix)-1):
  for j in range(i+1, len(matrix)):
    a = matrix[i]
    b = matrix[j]
    cos_sim = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
    if cos_sim > cos_i_j[0]:
      cos_i_j = [cos_sim, i, j]
print(cos_i_j[0])
print(cos_i_j[1], data[cos_i_j[1]])
print(cos_i_j[2], data[cos_i_j[2]])

0.7715167498104595
8 What is your review of osquery?

27 What is your review of iPad Mini 2?



**Вывод:** наиболее близкие строки под номером 8 и 27.